services:
  # Serviço  API
  api:
    build: .
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db 
      - ./data:/app/data 

  # (ETL)
  ingestor:
    build: .
    command: python app/ingest.py
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db # volume da API
      - ./data:/app/data # Lê os PDFs
